# Generated by Django 3.2 on 2020-12-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='year',
        ),
    ]
