# Generated by Django 3.2 on 2020-12-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_places_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name_plural': 'places'},
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.places')),
            ],
        ),
    ]
