# Generated by Django 3.2 on 2020-12-04 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name_plural': 'places'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='userid',
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.category'),
            preserve_default=False,
        ),
    ]
