# Generated by Django 3.2 on 2020-12-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20201205_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.places'),
            preserve_default=False,
        ),
    ]
